[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
solball = "bf58XNfg83MbH4WQBz9EYHcq2v9EP1VqPmZZqcasqSQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./my-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
