[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solball = "4ddavkocvoin1ZTeJcHrgtZHjN3ETEhwPh3jWE26qV7U"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = './my-keypair.json'

[scripts]
test = "yarn run -p ./tsconfig.json -t 1000000 ./solball/test/test.tests.ts"
