import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import PrivvyProvider from "../providers/PrivyProvider";
import AppProvider from "../providers/WalletProvider";
import { DynaPuff } from "next/font/google";

const dynapuff = DynaPuff({
  subsets: ["latin"], // adjust subsets if needed
  variable: "--font-dynapuff",
  display: "swap",
  weight: ["400", "500", "600", "700"], // include all available weights
  style: ["normal"], // include both styles
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dynapuff.className}>
        <PrivvyProvider>
          <AppProvider>{children}</AppProvider>
        </PrivvyProvider>
      </body>
    </html>
  );
}
