import type { Metadata } from "next";
import "./globals.css";
import PrivvyProvider from "../providers/PrivyProvider";
import { DynaPuff } from "next/font/google";
import { NavTabs } from "@/components/NavTabs";
import ProfileProvider from "@/providers/ProfileProvider";

const dynapuff = DynaPuff({
  subsets: ["latin"], // adjust subsets if needed
  variable: "--font-dynapuff",
  display: "swap",
  weight: ["400", "500", "600", "700"], // include all available weights
  style: ["normal"], // include both styles
});
export const metadata: Metadata = {
  title: "SolBall ⚽️",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dynapuff.className}>
        <PrivvyProvider>
          <ProfileProvider>
            <NavTabs />
            {children}
          </ProfileProvider>
        </PrivvyProvider>
      </body>
    </html>
  );
}
